name: Solana Anchor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Solana Anchor Program
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      # Install Solana CLI tools
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/install)"

      # Install Anchor CLI
      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked

      # Build the Anchor program
      - name: Build Anchor program
        run: |
          anchor build

      # Run tests
      - name: Run tests
        run: |
          anchor test

