[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]

[lib]
crate-type = ["cdylib", "lib"]
name = "{{project-name}}"

[dependencies]
anchor-lang = "0.29.0"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

